name: PipelineFlask
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Teste
        run: coverage run app_test.py

      - name: Relatorio do teste
        run: coverage report -m

      - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-crr8jkbv2p9s73cl0l40
          api-key: rnd_CawuSTcR5Tv5NNPc7PYGW85IbFNL

      - name: Deploy no EC2 -AWS
        run: |
          echo "Conectando no EC2"
          echo "${{secrets.AWS_CHAVE_PIPELINE_AWS_PEM}}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-54-197-35-208.compute-1.amazonaws.com "
          cd Aws_pipeline/;git pull;cd python_flask/;./executar.sh"
